version: '3.4'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak-nodejs-example-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: "scripts"
    entrypoint: "/opt/keycloak/bin/kc.sh"
    command:
      - "start-dev --import-realm"
    ports:
      - 8080:8080
    volumes:
      - "./docker/import_realm_users:/opt/keycloak/data/import"